spring:
  profiles.active: local-sys

---

spring:
  profiles: local-sys

am.datasource:
  url: jdbc:mysql://localhost:3306/sys
  username: root
  password: 'root'
  driver-class-name: com.mysql.jdbc.Driver
