spring:
  profiles.active: local

---

spring:
  profiles: local

am.datasource:
  url: jdbc:mysql://localhost:3306/store
  username: root
  password: 'root'
  driver-class-name: com.mysql.jdbc.Driver

